# Generated by Django 4.1.7 on 2023-05-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0002_likerecipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="n_of_likes",
            field=models.IntegerField(default=0),
        ),
    ]
