# Generated by Django 4.1.7 on 2023-05-30 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0004_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="difficulty",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
